# Generated by Django 5.2 on 2026-03-31 00:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamaVariabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_variabel', models.CharField(max_length=255, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nama Variabel',
                'verbose_name_plural': 'Nama Variabel',
                'ordering': ['nama_variabel'],
            },
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_wilayah', models.CharField(max_length=255)),
                ('tipe_wilayah', models.CharField(choices=[('Negara', 'Negara'), ('Provinsi', 'Provinsi'), ('Kabupaten', 'Kabupaten'), ('Kota', 'Kota')], max_length=50)),
                ('kode_wilayah', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Wilayah',
                'verbose_name_plural': 'Wilayah',
                'ordering': ['tipe_wilayah', 'nama_wilayah'],
            },
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField(db_index=True)),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variabel_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.namavariabel')),
                ('wilayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wilayah')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'ordering': ['wilayah', 'tahun', 'variabel_data'],
                'unique_together': {('wilayah', 'variabel_data', 'tahun')},
            },
        ),
    ]
