# Generated by Django 5.2 on 2026-03-17 11:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VariabelName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_variabel', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wilayah',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_wilayah', models.CharField(max_length=255)),
                ('tipe_wilayah', models.CharField(choices=[('Provinsi', 'Provinsi'), ('Kabupaten', 'Kabupaten'), ('Kota', 'Kota')], max_length=50)),
                ('kode_wilayah', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tahun', models.IntegerField()),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variabel_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.variabelname')),
                ('wilayah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wilayah')),
            ],
            options={
                'unique_together': {('wilayah', 'variabel_data', 'tahun')},
            },
        ),
    ]
