# Generated by Django 5.2 on 2026-03-31 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KategoriVariabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(max_length=100, unique=True)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('urutan', models.PositiveSmallIntegerField(default=0, help_text='Urutan tampil di filter/UI (0 = paling atas)')),
            ],
            options={
                'verbose_name': 'Kategori Variabel',
                'verbose_name_plural': 'Kategori Variabel',
                'ordering': ['urutan', 'nama_kategori'],
            },
        ),
        migrations.AlterModelOptions(
            name='namavariabel',
            options={'ordering': ['kategori__urutan', 'kategori__nama_kategori', 'nama_variabel'], 'verbose_name': 'Nama Variabel', 'verbose_name_plural': 'Nama Variabel'},
        ),
        migrations.AddField(
            model_name='namavariabel',
            name='kategori',
            field=models.ForeignKey(blank=True, help_text='Kelompok/kategori variabel ini (isi lewat Admin, opsional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variabel', to='app.kategorivariabel'),
        ),
    ]
