# Generated by Django 5.2 on 2026-03-31
# Modified: Gunakan RunSQL agar tidak butuh GeoDjango saat migrasi

from django.db import migrations


class Migration(migrations.Migration):
    """
    Hapus kolom geom dari tabel app_wilayah.
    Geometry kini disimpan sebagai file GeoJSON statis di static/geojson/.
    Menggunakan RunSQL (bukan RemoveField) agar tidak butuh GDAL/GeoDjango.
    """

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        # Pakai raw SQL agar tidak bergantung pada GeoDjango field type resolution
        migrations.RunSQL(
            sql="ALTER TABLE app_wilayah DROP COLUMN IF EXISTS geom;",
            reverse_sql="SELECT 1;",  # Tidak bisa di-rollback (data sudah di file GeoJSON)
        ),
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op di server yg kolom geom sudah tidak ada
            reverse_sql="SELECT 1;",
        ),
    ]
