# Generated by Django 5.2 on 2026-03-17 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VariabelName',
            new_name='DataName',
        ),
    ]
