# Generated by Django 5.2 on 2026-03-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_variabelname_dataname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilayah',
            name='tipe_wilayah',
            field=models.CharField(choices=[('Negara', 'Negara'), ('Provinsi', 'Provinsi'), ('Kabupaten', 'Kabupaten'), ('Kota', 'Kota')], max_length=50),
        ),
    ]
