# Generated by Django 5.2 on 2026-03-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_wilayah_tipe_wilayah'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DataName',
            new_name='Nama_Variabel',
        ),
    ]
