# Generated by Django 5.2 on 2026-03-17 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_dataname_nama_variabel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nama_Variabel',
            new_name='NamaVariabel',
        ),
    ]
