# Generated by Django 5.2 on 2026-03-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_nama_variabel_namavariabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wilayah',
            name='kode_wilayah',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
