# Generated by Django 5.2 on 2026-03-27 15:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_wilayah_kode_wilayah'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilayah',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
